services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
  web:
    build: ./frontend
    environment:
      - VITE_API_URL=http://localhost:8000
    ports:
      - "5173:5173"
    depends_on:
      - api
